name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Triggers deployment on every push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python (needed for EB CLI)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Elastic Beanstalk CLI
        run: pip install awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init "${{ secrets.EB_APP_NAME }}" --region "${{ secrets.AWS_REGION }}" --platform "Docker"
          eb use "${{ secrets.EB_ENV_NAME }}"
          eb deploy
